### PR TITLE
fix(api): do not duplicate payload in build params for hooks

### LINKED ISSUE #4948: fix(payload): variable set 2 times
Hello,

I call a webhook, with a JSON in payload, and the worflow start with 2 times the variable "payload" set... Why ?

Send me a messsage internaly.

Tx

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <5719034+bnjjj@users.noreply.github.com>

1. Description
1. Related issues
close #4948 
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/api/workflow_run_test.go [hunk 1]
```diff
@@ -1887,7 +1909,175 @@ func Test_postWorkflowRunHandlerHookWithMutex(t *testing.T) {
...
+	}
+	test.NoError(t, pipeline.InsertJob(api.mustDB(), j, s.ID, &pip2))
+	s.Jobs = append(s.Jobs, *j)
+
+	mockServiceHook, _ := assets.InsertService(t, db, "Test_postWorkflowRunHandlerHookWithMutex", services.TypeHooks)
+	defer func() {
+		_ = services.Delete(db, mockServiceHook) // nolint
+	}()
+
+	//This is a mock for the repositories service
```
Comment (yesnault) [inline engine/api/workflow_run_test.go]:
```suggestion
	//This is a mock for the hook service
```

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#12314.0 ■   
* Build
  * Build and Package All ■   
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ■   
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✔
