### PR TITLE
fix(api): add history length on workflow as code

### LINKED ISSUE #2527: missing history length on workflow as code

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
close #2527
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: sdk/exportentities/workflow.go [hunk 1]
```diff
@@ -77,6 +78,10 @@ func NewWorkflow(w sdk.Workflow, withPermission bool) (Workflow, error) {
 		}
 	}
 
+	if w.HistoryLength > 0 {
```
Comment (fsamin) [inline sdk/exportentities/workflow.go]: and if != default value (20)

Comment (bnjjj) [reply sdk/exportentities/workflow.go]: done
