### PR TITLE
fix(api): merge pipeline parameter and default value in workflow context

### LINKED ISSUE #3380: pipeline parameter and default value
workflow
```yml
name: testpip
version: v1.0
workflow:
  child:
    depends_on:
    - void
    when:
    - success
    pipeline: child
    parameters:
      foo: barAA
  void:
    pipeline: void
```

pipeline:
```yml
version: v1.0
name: child
parameters:
  foo:
    type: string
    default: bar
  foo2:
    type: string
    default: bar2
jobs:
- job: New Job
  steps:
  - script:
    - env
```

the pipeline parameter foo2 is not available in "Display job variables"

--> if the value of the parameter "foo" is equals to the default value, "foo2" is well available

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
close #3380
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: sdk/parameter.go [hunk 1]
```diff
@@ -175,6 +175,17 @@ func variablesToParameters(prefix string, variables []Variable) []Parameter {
 	return res
 }
 
+// ParameterspMerge merges two slices of parameters preserving all values
+func ParametersMerge(src []Parameter, dst []Parameter) []Parameter {
```
Comment (yesnault) [inline sdk/parameter.go]: it's not really a src / dst, overwritter?

**Comment by ovh-cds** [comment]
CDS Report ut-engine#6398.0 ✘  
* Stage 1
  * Engine Test with DB ✘  
Unit Tests Report
* github.com/ovh/cds/cli


* github.com/ovh/cds/engine/api






































































































































































































  * Test_postAndDeleteWorkflowLabelHandler ✘

* github.com/ovh/cds/engine/api/application








* github.com/ovh/cds/engine/api/environment




* github.com/ovh/cds/engine/api/keys



* github.com/ovh/cds/engine/api/migrate


* github.com/ovh/cds/engine/api/pipeline






* github.com/ovh/cds/engine/api/plugin


* github.com/ovh/cds/engine/api/project









* github.com/ovh/cds/engine/api/secret






* github.com/ovh/cds/engine/api/user








* github.com/ovh/cds/engine/api/warning















* github.com/ovh/cds/engine/api/worker











* github.com/ovh/cds/engine/api/workflow














































* github.com/ovh/cds/engine/hatchery/swarm



















* github.com/ovh/cds/engine/hooks






* github.com/ovh/cds/engine/repositories


* github.com/ovh/cds/engine/vcs











* github.com/ovh/cds/engine/vcs/bitbucket


















* github.com/ovh/cds/engine/vcs/github













* github.com/ovh/cds/engine/vcs/gitlab









* github.com/ovh/cds/engine/worker






* github.com/ovh/cds/sdk


















* github.com/ovh/cds/sdk/cdsclient



* github.com/ovh/cds/sdk/exportentities




























* github.com/ovh/cds/sdk/interpolate

























* github.com/ovh/cds/sdk/luascript





* github.com/ovh/cds/sdk/namesgenerator



* github.com/ovh/cds/sdk/vcs/git
