### PR TITLE
refactor(ui): don't load unecessary data and delete cache bugs from #1859

### LINKED ISSUE #1859: fix (ui): add pipeline then add workflow
the new pipeline in not listed when we add a new workflow (cache issue, after refresh, it's ok)

### PR DESCRIPTION
**Pull request by bnjjj**
close #1859

Signed-off-by: Benjamin Coenen <benjamin.coenen@hotmail.com>

### CODE REVIEW

File: sdk/common.go [hunk 1]
```diff
@@ -10,6 +10,11 @@ import (
 //EncryptFunc  is a common type
 type EncryptFunc func(gorp.SqlExecutor, int64, string, string) (string, error)
 
+type IDName struct {
```
Comment (fsamin) [inline sdk/common.go]: doc

File: engine/api/pipeline/pipeline.go [hunk 2]
```diff
@@ -80,6 +80,24 @@ func LoadPipeline(db gorp.SqlExecutor, projectKey, name string, deep bool) (*sdk
 	return &p, nil
 }
 
+// LoadPipelineID loads a pipeline from database
+func LoadPipelineID(db gorp.SqlExecutor, projectKey, name string) (int64, error) {
```
Comment (fsamin) [inline engine/api/pipeline/pipeline.go]: i don't see any usage of this

File: engine/api/project/dao.go [hunk 3]
```diff
@@ -245,6 +245,7 @@ var LoadOptions = struct {
 	WithVariablesWithClearPassword LoadOptionFunc
 	WithPipelines                  LoadOptionFunc
 	WithPipelineNames              LoadOptionFunc
+	WithPipelineNamesIDs           LoadOptionFunc
```
Comment (fsamin) [inline engine/api/project/dao.go]: seems useless since you don't initialize it
