### PR TITLE
fix(api,hooks): rename workflow as-code

### LINKED ISSUE #4118: unable to rename workflow from as-code
```
[2019-03-28T12:43:48] ⚠ An error has occured: GoRoutine>postWorkflowRunHandler>initWorkflowRun>CreateFromRepository>extractWorkflow>Push>Update>insertNode>insertHook: internal server error (caused by: unable to get workflow from repository.: extractWorkflow> Unable to get workflow from file: Unable to update workflow: unable to update root node on workflow(6325): Unable to insert workflow node hook: Unable to insert hook: pq: duplicate key value violates unique constraint "workflow_node_hook_uuid_key")

### PR DESCRIPTION
**Pull request by fsamin**
and avoid deleting all hooks execution

close #4118

### CODE REVIEW

File: engine/api/workflow/dao.go [hunk 1]
```diff
@@ -1600,101 +1508,72 @@ func Push(ctx context.Context, db *gorp.DbMap, store cache.Store, proj *sdk.Proj
...
 
-			if wf.Root.Context.Application != nil {
-				if err := application.Update(tx, store, wf.Root.Context.Application); err != nil {
-					return nil, nil, sdk.WrapError(err, "Unable to update application vcs datas")
-				}
-			}
-		}
+	wf, msgList, err := ParseAndImport(ctx, tx, store, proj, oldWf, &data.wrkflw, u, importOptions)
+	if err != nil {
+		log.Error("Push> Unable to import workflow: %v", err)
```
Comment (sguiheux) [inline engine/api/workflow/dao.go]: do we really need this log?

File: engine/api/workflow/workflow_importer.go [hunk 2]
```diff
@@ -88,11 +88,9 @@ func Import(ctx context.Context, db gorp.SqlExecutor, store cache.Store, proj *s
 		return sdk.WrapError(err, "Unable to update workflow")
 	}
 
-	if !dryRun {
-		// HookRegistration after workflow.Update.  It needs hooks to be created on DB
-		if errHr := HookRegistration(ctx, db, store, oldW, *w, proj); errHr != nil {
-			return sdk.WrapError(errHr, "Cannot register hook")
-		}
+	// HookRegistration after workflow.Update.  It needs hooks to be created on DB
```
Comment (sguiheux) [inline engine/api/workflow/workflow_importer.go]: do we need if defaultBranch?

File: engine/hooks/hooks_handlers.go [hunk 3]
```diff
@@ -399,13 +400,17 @@ func (s *Service) postTaskBulkHandler() service.Handler {
 		}
 
 		for _, hook := range hooks {
-			if hook.UUID != "" {
-				if err := s.deleteTask(ctx, &hook); err != nil {
-					log.Warning("Hooks> postTaskBulkHandler cannot delete task %s : %v", hook.UUID, err)
+			if hook.UUID == "" {
```
Comment (sguiheux) [inline engine/hooks/hooks_handlers.go]: UUID must not be empty, insertNode set UUID

File: engine/api/workflow/repository.go [hunk 4]
```diff
@@ -136,6 +145,92 @@ func ReadCDSFiles(files map[string][]byte) (*tar.Reader, error) {
...
+				log.Error("two workflows files found: %s and %s", workflowFileName, hdr.Name)
+				mError.Append(fmt.Errorf("two workflows files found: %s and %s", workflowFileName, hdr.Name))
+				break
+			}
+			if err := yaml.Unmarshal(b, &res.wrkflw); err != nil {
+				log.Error("Push> Unable to unmarshal workflow %s: %v", hdr.Name, err)
+				mError.Append(fmt.Errorf("Unable to unmarshal workflow %s: %v", hdr.Name, err))
+				continue
+			}
+			workflowFileName = hdr.Name
```
Comment (golangcibot) [inline engine/api/workflow/repository.go]: SA4006: this value of `workflowFileName` is never used (from `staticcheck`)

File: engine/api/workflow/dao.go (hunk 1 above)
Comment (fsamin) [reply engine/api/workflow/dao.go]: removed

File: engine/api/workflow/workflow_importer.go (hunk 2 above)
Comment (fsamin) [reply engine/api/workflow/workflow_importer.go]: done with `derivationBranch`

File: engine/hooks/hooks_handlers.go (hunk 3 above)
Comment (fsamin) [reply engine/hooks/hooks_handlers.go]: done

File: engine/api/workflow/repository.go (hunk 4 above)
Comment (fsamin) [reply engine/api/workflow/repository.go]: done
