### PR TITLE
fix(api): update scheduler

### LINKED ISSUE #4250: fix(hooks): edit scheduler -> next execution
next execution (even if planned) should be updated after edit on scheduler

### PR DESCRIPTION
**Pull request by yesnault**
- edit scheduler: next execution is deleted and re-scheduled
- edit as code / workflow push: take new hook config if present
- cdsctl: ignore case on filter

close #4250

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

File: engine/hooks/hooks_handlers.go [hunk 1]
```diff
@@ -463,6 +463,16 @@ func (s *Service) updateTask(ctx context.Context, h *sdk.WorkflowNodeHook) error
 	}
 
 	task.Config = t.Config
+	s.stopTask(t)
```
Comment (golangcibot) [inline engine/hooks/hooks_handlers.go]: Error return value of `s.stopTask` is not checked (from `errcheck`)

**Comment by ovh-cds** [comment]
CDS Report build-engine-cli-tools#9439.0 ■   
* Build minimal
  * cdsctl linux ✔ 
  * check SQL Files number ✔ 
  * Engine Build linux amd64 ✔ 
  * tools/debpacker ✔ 
  * tools/os-ansible-inventory ✔ 
  * Worker linux amd64 / 386 ✔ 
* Build other os/arch
  * cdsctl freebsd windows amd64 ✔ 
  * cdsctl openbsd amd64 ✔ 
  * Doc Build -   
  * Engine Build darwin amd64 ✔ 
  * Engine Build freebsd amd64 ✔ 
  * Engine Build linux arm/arm64 ✔ 
  * Engine Build openbsd amd64 ✔ 
  * Engine Build windows amd64 ✔ 
  * Plugins darwin amd64 ✔ 
  * Plugins freebsd ✔ 
  * Plugins integrations K8S -   
  * Plugins linux amd64 ✔ 
  * Plugins linux arm ✔ 
  * Plugins linux arm64 ✔ 
  * Plugins openbsd ✔ 
  * Plugins windows amd64 ✔ 
  * Worker darwin / windows / freebsd / openbsd ✔ 
  * Worker linux arm ✔ 
* Package
  * Debian Engine Package ■   
  * Docker Engine Package ■

**Comment by ovh-cds** [comment]
CDS Report build-ui#9439.0 ■   
* Compile
  * Build UI ■   
  * TU All -   
  * TU model ■   
  * TU service ■   
  * TU shared ■   
  * TU store ■   
  * TU views ■

**Comment by ovh-cds** [comment]
CDS Report ut-engine#9439.0 ■   
* Stage 1
  * Engine Test with DB ■
