### PR TITLE
fix (worker): add info on err with tmpl. Closes #935

### LINKED ISSUE #935: fix (worker): add info on err with tmpl
here -> https://github.com/ovh/cds/blob/master/engine/worker/cmd_tmpl.go#L79 and all below.

Use sendLog

### PR DESCRIPTION
**Pull request by fsamin**
Signed-off-by: François Samin <francois.samin@corp.ovh.com>

### CODE REVIEW

File: engine/worker/cmd_server.go [hunk 1]
```diff
@@ -58,3 +60,18 @@ func (w *currentWorker) serve(c context.Context) (int, error) {
...
+	w.Header().Add("Content-Type", "application/json")
+	w.WriteHeader(status)
+	w.Write(b)
+}
+
+func writeError(w http.ResponseWriter, r *http.Request, err error) {
+	al := r.Header.Get("Accept-Language")
+	msg, code := sdk.ProcessError(err, al)
+	sdkErr := sdk.Error{Message: msg}
+	log.Info("Write error: %s\n", sdkErr)
```
Comment (yesnault) [inline engine/worker/cmd_server.go]: \n
