### PR TITLE
fix(api): push artifact on object store with ref instead of tag

### LINKED ISSUE #2662: fix(api): on artifact upload with a tag containing '/' it seems it's replaced with a '-'

### PR DESCRIPTION
**Pull request by bnjjj**
1. Description
1. Related issues
close #2662 
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/api/migrate/workflow_node_run_artifacts.go [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+	db := DBFunc()
+	log.Info("WorkflowNodeRunArtifacts> Begin")
+
+	wfrArtifacts := []struct {
+		ID  int64          `db:"id"`
+		Ref sql.NullString `db:"ref"`
+		Tag string         `db:"tag"`
+	}{}
+
+	if _, err := db.Select(&wfrArtifacts, "SELECT id, ref, tag FROM workflow_node_run_artifacts"); err != nil {
```
Comment (yesnault) [inline engine/api/migrate/workflow_node_run_artifacts.go]: where
