### PR TITLE
 fix (api): avoid sending notif on default group

### LINKED ISSUE #2275: fix (api): avoid sending jabb notif on default group

### PR DESCRIPTION
**Pull request by yesnault**
close #2275

### CODE REVIEW

File: engine/api/group.go [hunk 1]
```diff
@@ -195,6 +195,7 @@ func (api *API) getGroupsHandler() Handler {
 		var err error
 
 		public := r.FormValue("withPublic")
+		withoutDefault := r.FormValue("withoutDefault")
```
Comment (bnjjj) [inline engine/api/group.go]: use `FormBool(r, "withoutDefault")` is better I think

File: ui/src/app/service/group/group.service.ts [hunk 2]
```diff
@@ -31,6 +31,14 @@ export class GroupService {
         return this._http.get<Group[]>('/group');
     }
 
+    /**
+     * Get all groups that the user can access, without the default group.
+     * @returns {Observable<Group[]>}
+     */
+    getGroupsWithoutDefault(): Observable<Group[]> {
```
Comment (bnjjj) [inline ui/src/app/service/group/group.service.ts]: why not pass an optional parameters to `getGroups(withoutDefault?: boolean)` and then use http query parameters of angular
