### PR TITLE
fix(engine): environment variables configuration

### LINKED ISSUE #3955: fix(engine): environment config variables
the `engine config new --env` command fails to display correctly the right environment variables

```bash
$ engine config new --env

export CDS_VCS_SERVERS="map[Github:{https://github.com 0xc0000c6600 <nil> <nil>} Bitbucket:{https://mybitbucket.com <nil> <nil> 0xc0000c6660} Gitlab:{https://gitlab.com <nil> 0xc00032eac0 <nil>}]"
```

cc @nledez

### PR DESCRIPTION
**Pull request by fsamin**
1. Description
Now using go-dump to generate environment variables. 
Diff is available here: https://pastebin.com/4W8dxZHm

1. Related issues
closes #3955

1. About tests
1. Mentions
@ovh/cds
@nledez

### CODE REVIEW

File: engine/config.go [hunk 1]
```diff
@@ -156,6 +157,20 @@ func configBootstrap(args []string) {
...
+// asEnvVariables returns the object attributes as env variables. It used for configuration structs
+func asEnvVariables(o interface{}) map[string]string {
+	dumper := dump.NewDefaultEncoder()
+	dumper.DisableTypePrefix = true
+	dumper.Separator = "_"
+	dumper.Prefix = "CDS"
+	dumper.Formatters = []dump.KeyFormatterFunc{dump.WithDefaultUpperCaseFormatter()}
+	envs, _ := dumper.ToStringMap(o)
+	for k := range envs {
+		viper.BindEnv(dumper.ViperKey(k), k)
```
Comment (golangcibot) [inline engine/config.go]: Error return value of `viper.BindEnv` is not checked (from `errcheck`)
