### PR TITLE
fix(sdk): do not export default payload in as-code

### LINKED ISSUE #4116: workflow as code should not export default payload

### PR DESCRIPTION
**Pull request by fsamin**
close #4116

### CODE REVIEW

File: sdk/exportentities/workflow.go [hunk 1]
```diff
@@ -336,6 +257,15 @@ func WorkflowSkipIfOnlyOneRepoWebhook(w sdk.Workflow, exportedWorkflow *Workflow
 		if nodeName == w.Root.Name && len(hs) == 1 {
 			if hs[0].Model == sdk.RepositoryWebHookModelName {
 				delete(exportedWorkflow.Hooks, nodeName)
+				if exportedWorkflow.Workflow != nil {
+					for nodeName := range exportedWorkflow.Workflow {
+						if nodeName == w.Root.Name {
+							entry := exportedWorkflow.Workflow[nodeName]
+							entry.Payload = nil
+							exportedWorkflow.Workflow[nodeName] = entry
```
Comment (bnjjj) [inline sdk/exportentities/workflow.go]: missing break ?
