### PR TITLE
fix(cdsctl): debug filters and fields options for list result

### LINKED ISSUE #4110: --filter option of cdsctl workflow history is broken
With -q option `cdsctl` print blank lines

Without other option print wrong output (line with 10->4)
```
cdsctl workflow history PCS cicd.models --filter status=Success
+--------------------------------+-----+--------------------------------+---------+
|         LAST EXECUTION         | NUM |             START              | STATUS  |
+--------------------------------+-----+--------------------------------+---------+
| 2019-03-27 08:47:09.3069 +0100 |  14 | 2019-03-27 08:40:06.360439     | Success |
| CET                            |     | +0100 CET                      |         |
| 2019-03-27 07:37:06.459072     |  13 | 2019-03-27 07:29:40.846239     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
| 2019-03-26 16:18:26.671624     |  12 | 2019-03-26 16:11:09.943092     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
| 2019-03-26 09:43:05.850219     |  11 | 2019-03-26 09:36:53.938994     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
|                             10 |
|                              9 |
|                              8 |
|                              7 |
|                              6 |
|                              5 |
|                              4 |
| 2019-03-26 07:18:30.394878     |   3 | 2019-03-26 07:15:20.508327     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
| 2019-03-26 07:12:28.013362     |   2 | 2019-03-26 07:09:57.673836     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
|                              1 |
+--------------------------------+-----+--------------------------------+---------+
```
Same with `--format yaml` format
```
cdsctl workflow history PCS cicd.models --filter status=Success --format yaml
- last_execution: 2019-03-27 08:47:09.3069 +0100 CET
  num: "14"
  start: 2019-03-27 08:40:06.360439 +0100 CET
  status: Success
- last_execution: 2019-03-27 07:37:06.459072 +0100 CET
  num: "13"
  start: 2019-03-27 07:29:40.846239 +0100 CET
  status: Success
- last_execution: 2019-03-26 16:18:26.671624 +0100 CET
  num: "12"
  start: 2019-03-26 16:11:09.943092 +0100 CET
  status: Success
- last_execution: 2019-03-26 09:43:05.850219 +0100 CET
  num: "11"
  start: 2019-03-26 09:36:53.938994 +0100 CET
  status: Success
- num: "10"
- num: "9"
- num: "8"
- num: "7"
- num: "6"
- num: "5"
- num: "4"
- last_execution: 2019-03-26 07:18:30.394878 +0100 CET
  num: "3"
  start: 2019-03-26 07:15:20.508327 +0100 CET
  status: Success
- last_execution: 2019-03-26 07:12:28.013362 +0100 CET
  num: "2"
  start: 2019-03-26 07:09:57.673836 +0100 CET
  status: Success
- num: "1"
```

Again with `--fields` options:
```
cdsctl workflow history PCS cicd.models --filter status=Success --fields num
+--------------------------------+-----+--------------------------------+---------+
|         LAST EXECUTION         | NUM |             START              | STATUS  |
+--------------------------------+-----+--------------------------------+---------+
| 2019-03-27 08:47:09.3069 +0100 |  14 | 2019-03-27 08:40:06.360439     | Success |
| CET                            |     | +0100 CET                      |         |
| 2019-03-27 07:37:06.459072     |  13 | 2019-03-27 07:29:40.846239     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
| 2019-03-26 16:18:26.671624     |  12 | 2019-03-26 16:11:09.943092     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
| 2019-03-26 09:43:05.850219     |  11 | 2019-03-26 09:36:53.938994     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
|                             10 |
|                              9 |
|                              8 |
|                              7 |
|                              6 |
|                              5 |
|                              4 |
| 2019-03-26 07:18:30.394878     |   3 | 2019-03-26 07:15:20.508327     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
| 2019-03-26 07:12:28.013362     |   2 | 2019-03-26 07:09:57.673836     | Success |
| +0100 CET                      |     | +0100 CET                      |         |
|                              1 |
+--------------------------------+-----+--------------------------------+---------+
```

### PR DESCRIPTION
**Pull request by richardlt**
1. Description
1. Related issues
close #4110 
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: cli/cobra.go [hunk 1]
```diff
@@ -310,6 +310,9 @@ func newCommand(c Command, run interface{}, subCommands SubCommands, mods ...Com
 				t := strings.Split(filter, " ")
 				for i := range t {
 					s := strings.SplitN(t[i], "=", 2)
+					if len(s) != 2 {
```
Comment (fsamin) [inline cli/cobra.go]: SplitN
