### PR TITLE
fix(api): support utf8 in mail subject

### LINKED ISSUE #5351: Mail notification and UTF-8 "Title"
If an email notification is created with a Title containing UTF-8 chars, like:
```
[release 🚀] {{.git.message}}
```
the encoding is not declared in the Subject header, so the mail reader can not render it correctly:
```
[release ðŸš€] …
```
To avoid doing it by ourselves:
```
=?UTF-8?Q?[release =f0=9f=9a=80]?= {{.git.message}}
```
Shouldn't the mail subject be automatically encoded using RFC 2047 if an UTF-8 character is detected?

### PR DESCRIPTION
**Pull request by fsamin**
close #5351

Signed-off-by: francois  samin <francois.samin@corp.ovh.com>

### CODE REVIEW

**Review by sguiheux — APPROVED** [review]

**Review by yesnault — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report build-all-cds#14543.0 ✘  
* Build
  * Build and Package All ✔ 
  * Build Debpacker ✔ 
  * Build OS-Ansible-Inventory ✔ 
  * Build SMTPMock ✔ 
  * Docs -   
  * Lint UI Translate ✔ 
  * Test CLI ✔ 
  * Test Engine ✔ 
  * Test SDK ✔ 
  * Test SDK Rust ✔ 
  * Test UI ✘

**Review by richardlt — APPROVED** [review]

File: engine/api/mail/mail.go [hunk 1]
```diff
@@ -183,7 +185,12 @@ func SendEmail(ctx context.Context, subject string, mailContent *bytes.Buffer, u
 	headers := make(map[string]string)
 	headers["From"] = smtpFrom
 	headers["To"] = to.String()
-	headers["Subject"] = subject
+	if sdk.StringIsAscii(subject) {
+		headers["Subject"] = subject
+	} else {
+		// https://tools.ietf.org/html/rfc2047
+		headers["Subject"] = "=?UTF-8?Q?" + subject + "?="
```
Comment (maxatome) [inline engine/api/mail/mail.go:192]: I don't think it is correct.

See `4.2. The "Q" encoding` in https://tools.ietf.org/html/rfc2047, non ascii bytes in `subject` have to be encoded as `=HH`.
