### PR TITLE
fix (worker): use API Remote Time

### LINKED ISSUE #2091: worker get queue
use timestamp of api and not timestamp or worker

this will avoid to install ntp everywhere workers are running if time is not sync with api

### PR DESCRIPTION
**Pull request by yesnault**
close #2091

feat (api): add process time in response headers

### CODE REVIEW

File: engine/api/router_util.go [hunk 1]
```diff
@@ -64,10 +67,24 @@ func writeNoContentPostMiddleware(ctx context.Context, w http.ResponseWriter, re
...
 		}
 	}
+	writeProcessTime(w)
 	w.WriteHeader(http.StatusNoContent)
 	return ctx, nil
 }
 
+func writeProcessTime(w http.ResponseWriter) {
+	for k, v := range w.Header() {
+		if k == cdsclient.ResponseAPITSTimeHeader && len(v) == 1 {
```
Comment (fsamin) [inline engine/api/router_util.go]: why not just w.Header().Get ?

File: sdk/cdsclient/http.go [hunk 2]
```diff
@@ -26,6 +26,17 @@ const (
 	RequestedWithValue = "X-CDS-SDK"
 	// RequestedNameHeader is used as HTTP header
 	RequestedNameHeader = "X-Requested-Name"
+	// RequestedIfModifiedSinceHeader is used as HTTP header
+	RequestedIfModifiedSinceHeader = "If-Modified-Since"
+
+	// ResponseAPITimeHeader is used as HTTP header
+	ResponseAPITimeHeader = "X-Api-Time"
+	// ResponseAPITSTimeHeader is used as HTTP header
+	ResponseAPITSTimeHeader = "X-Api-Ts-Time"
```
Comment (fsamin) [inline sdk/cdsclient/http.go]: Ts ?

**Comment by yesnault** [comment]
@fsamin done
