### PR TITLE
fix(hatchery/swarm): don't try to remove docker bridge

### LINKED ISSUE #2733: Log in hatchery swarm on pre-defined network
Log in hatchery swarm
````
killAndRemove> unable to kill and remove network f0b4c78490bd err:Error response from daemon: bridge is a pre-defined network and cannot be removed
```

And there is no service link on pre-requisite on the job

### PR DESCRIPTION
**Pull request by fsamin**
close #2733

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/hatchery/swarm/swarm_util_kill.go [hunk 1]
```diff
@@ -39,6 +39,11 @@ func (h *HatcherySwarm) killAndRemove(ID string) error {
 			continue
 		}
 
+		//If it's the default docker bridge... skip
+		if network.Driver != "bridge" || network.Name == "docker0" || network.Name == "bridge" {
```
Comment (golangci) [inline engine/hatchery/swarm/swarm_util_kill.go]: string `bridge` has 4 occurrences, make it a constant
