### PR TITLE
fix(hooks): delete the branch deletion when this branch is pushed again #4553

### LINKED ISSUE #4553: fix(hooks): when a branch is deleted and pushed again it doesn't delete the delete run task

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
close #4553 
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/hooks/branch_deletion.go [hunk 1]
```diff
@@ -15,3 +15,21 @@ func (s *Service) doBranchDeletionTaskExecution(t *sdk.TaskExecution) (*sdk.Work
 
 	return nil, sdk.WrapError(err, "cannot mark to delete workflow runs")
 }
+
+func (s *Service) stopBranchDeletionTask(branch string) error {
+	keys, err := s.Dao.FindAllKeysMatchingPattern(branch + "*")
```
Comment (yesnault) [inline engine/hooks/branch_deletion.go]: could you add a check to check if branch is not empty (to avoid drop everything)

Comment (bnjjj) [reply engine/hooks/branch_deletion.go]: Good idea ! Haha
