### PR TITLE
fix(api): error inserting UpdateSpawnErrorWorkerModel with UTF8 0x00

### LINKED ISSUE #4055: WorkerModelSpawnError: internal server error
```
019-03-19 17:13:40 [WARN] pprofLabel>recoverWrap>Handle>spawnErrorWorkerModelHandler>UpdateSpawnErrorWorkerModel: internal server error (caused by: cannot update spawn error on worker model: pq: invalid byte sequence for encoding "UTF8": 0x00) error_uuid=f5b61728-4a61-11e9-9670-6a0002fa6430 method=PUT request_uri=/worker/model/error/1 stack_trace=pq: invalid byte sequence for encoding "UTF8": 0x00
```

### PR DESCRIPTION
**Pull request by fsamin**
1. Description
1. Related issues
close #4055
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/api/worker/model.go [hunk 1]
```diff
@@ -426,6 +426,10 @@ func updateAllToCheckRegistration(db gorp.SqlExecutor) error {
 
 // UpdateSpawnErrorWorkerModel updates worker model error registration
 func UpdateSpawnErrorWorkerModel(db gorp.SqlExecutor, modelID int64, spawnError sdk.SpawnErrorForm) error {
+	if spawnError.Error == string([]byte{0x00}) {
```
Comment (richardlt) [inline engine/api/worker/model.go]: When is this happening ? Can you add a comment ?

Comment (fsamin) [reply engine/api/worker/model.go]: some times when the docker container fails to start, the docker logs is not empty but only contains utf8 null char

Comment (fsamin) [reply engine/api/worker/model.go]: comment added
