### PR TITLE
fix(plugin/venom): files with coma

### LINKED ISSUE #4700: plugin-venom: files with coma
example of path:

```/tmp/VGVzdHM/run/tests/e2e/aa.yml,/tmp/VGVzdHM/run/tests/e2e/public/bb.yml,/tmp/VGVzdHM/run/tests/e2e/public/cc.yml,/tmp/VGVzdHM/run/tests/e2e/admin/dd.yml,/tmp/VGVzdHM/run/tests/e2e/admin/ee.yml```

seems trigger only test on last file

### PR DESCRIPTION
**Pull request by yesnault**
close #4700

and various ui fixes

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

File: contrib/grpcplugins/action/venom/main.go [hunk 1]
```diff
@@ -166,25 +166,31 @@ func (actPlugin *venomActionPlugin) Run(ctx context.Context, q *actionplugin.Act
...
 	}
 
 	if len(filepathExcluded) == 1 {
 		filepathExcluded = strings.Split(filepathExcluded[0], " ")
 	}
 
+	var filepathExcludedComputed []string
 	for _, fp := range filepathExcluded {
-		filepathExcluded, err = walkGlobFile(fp)
+		a, err := walkGlobFile(fp)
```
Comment (bnjjj) [inline contrib/grpcplugins/action/venom/main.go]: what is `a` ?

File: contrib/grpcplugins/action/venom/main.go [hunk 2]
```diff
@@ -166,25 +166,31 @@ func (actPlugin *venomActionPlugin) Run(ctx context.Context, q *actionplugin.Act
 		filepathVal = strings.Split(filepathVal[0], " ")
 	}
 
+	var filepathValComputed []string
 	for _, fp := range filepathVal {
-		filepathVal, err = walkGlobFile(fp)
+		a, err := walkGlobFile(fp)
```
Comment (bnjjj) [inline contrib/grpcplugins/action/venom/main.go]: what is `a` ?
