### PR TITLE
fix(api): workflow push with platform in context

### LINKED ISSUE #2825: Workflow push won't save pipeline/platform associations
```yml
  deploy-playground-eu:
    depends_on:
    - build-image-playground-eu
    when:
    - success
    pipeline: deploy-platform
    application: Lhasa
    platform: containers-dev
```

```
$ cdsctl workflow push URBA .cds/*.yml
$ git diff
```
```diff
diff --git a/.cds/LhasaWorkflow.yml b/.cds/LhasaWorkflow.yml
index fb7fd2b..08cde2f 100644
--- a/.cds/LhasaWorkflow.yml
+++ b/.cds/LhasaWorkflow.yml
@@ -50,7 +50,6 @@ workflow:
     - success
     pipeline: deploy-platform
     application: Lhasa
-    platform: containers-dev
```

### PR DESCRIPTION
**Pull request by fsamin**
closes #2825

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/api/workflow/workflow_importer.go [hunk 1]
```diff
@@ -80,6 +81,19 @@ func Import(db gorp.SqlExecutor, store cache.Store, proj *sdk.Project, w *sdk.Wo
 	}
 	w.Visit(hookLoad)
 
+	var projectPlatfoformLoad = func(n *sdk.WorkflowNode) {
+		if n.Context != nil && n.Context.ProjectPlatform != nil && n.Context.ProjectPlatform.Name != "" {
+			ppf, err := platform.LoadPlatformsByName(db, proj.Key, n.Context.ProjectPlatform.Name, true)
+			if err != nil {
+				log.Warning("workflow.Import> %s > Project platform %s not found", n.Context.ProjectPlatform.Name)
```
Comment (yesnault) [inline engine/api/workflow/workflow_importer.go]: missing err in log?
