### PR TITLE
fix(worker): add retry on worker upload cmd

### LINKED ISSUE #3065: Add retry on worker command worker artifact upload

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
close #3065 
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-engine-cli-tools#5161.0 ✘  
* Build minimal
  * cds cli legacy ✔ 
  * cdsctl linux ✔ 
  * Engine Build linux amd64 ✔ 
  * tools/debpacker ✔ 
  * tools/os-ansible-inventory ✔ 
  * Worker linux amd64 / 386 ✘

File: engine/worker/cmd_cache.go [hunk 1]
```diff
@@ -135,9 +135,9 @@ func cachePushCmd(w *currentWorker) func(cmd *cobra.Command, args []string) {
 		}
 
 		client := http.DefaultClient
-		client.Timeout = 10 * time.Minute
+		client.Timeout = 30 * time.Minute
 
-		resp, errDo := client.Do(req)
+		resp, errDo := http.DefaultClient.Do(req)
```
Comment (fsamin) [inline engine/worker/cmd_cache.go]: client ?

Comment (bnjjj) [reply engine/worker/cmd_cache.go]: done
