### PR TITLE
fix(sdk): interpolate

### LINKED ISSUE #3421: interpolate
{{ .git.tag | default .cds.version }}

### PR DESCRIPTION
**Pull request by fsamin**
closes #3421

about: 
 - 20% perf penalty
 - 50% alloc penalty

### CODE REVIEW

File: sdk/interpolate/interpolate.go [hunk 1]
```diff
@@ -11,107 +12,144 @@ import (
...
 	// sort key, to replace the longer variables before
-	// see "same prefix" unit test
 	keys := make([]string, len(vars))
 	var i int64
 	for k := range vars {
 		keys[i] = k
 		i++
 	}
-	sort.Sort(reverseString(keys))
+	sort.Slice(keys, func(i, j int) bool {
```
Comment (richardlt) [inline sdk/interpolate/interpolate.go]: no more needed

Comment (fsamin) [reply sdk/interpolate/interpolate.go]: now we sort by number of dots
