### PR TITLE
 fix(api,ui): remove application deployment strategies

### LINKED ISSUE #2703: Several errors about platforms
####  when removing a platform linked to an application

```
curl 'https://interne.ovh.net/cds/ui/cdsapi/project/PROJECT_KEY/platforms/platform_name' -X DELETE -H 'Accept: application/json, text/plain, */*' -H 'Session-Token: xxx' --compressed
```
```json
{"message":"internal server error"}
```

#### can't remove a platform from the pipeline context

The UI seems to force a selected value

#### when a platform has been unlinked, pipeline contexts seems empty

But it is still impossible to remove the platform (500)

### PR DESCRIPTION
**Pull request by fsamin**
1. Description
1. Related issues
close #2703

1. About tests
1. Mentions
@ovh/cds

### CODE REVIEW

File: engine/api/workflow/dao.go [hunk 1]
```diff
@@ -954,3 +978,34 @@ func UpdateFavorite(db gorp.SqlExecutor, workflowID int64, u *sdk.User, add bool
...
+	WHERE workflow.project_id = $1
+	AND project_platform.name = $2
+	AND workflow_node_context.project_platform_id = project_platform.id
+	`
+
+	res := []sdk.Workflow{}
+	dbRes := []Workflow{}
+	if _, err := db.Select(&dbRes, query, projID, pfName); err != nil {
+		if err == sql.ErrNoRows {
+			return nil, sdk.ErrWorkflowNotFound
```
Comment (sguiheux) [inline engine/api/workflow/dao.go]: return empty slice or nil
