### PR TITLE
fix(ui): as code preview + add try catch on json.parse

### LINKED ISSUE #3542: renaming a workflow node doesn't change the as-code preview

### PR DESCRIPTION
**Pull request by sguiheux**
1. Description
1. Related issues
close #3542
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: ui/src/assets/worker/sharedWorker.js [hunk 1]
```diff
@@ -29,10 +29,14 @@ function initSSE(force) {
...
-            connections.forEach(p => {
-                p.postMessage(jsonEvent);
-            });
+            try {
+                var jsonEvent = JSON.parse(evt.data);
+                connections.forEach(p => {
+                    p.postMessage(jsonEvent);
+                });
+            } catch (error) {
+                console.log('Error parsing data: ', evt.data);
```
Comment (bnjjj) [inline ui/src/assets/worker/sharedWorker.js]:
```suggestion
                console.error('Error parsing data: ', evt.data);
```
