### PR TITLE
fix(api): delete binary capabilities from worker model when it doesn't exist (close #3557)

### LINKED ISSUE #3557: worker model with deleted binary
take care of a deleted binary from a worker model (actually, binary is listed in CDS even if it's deleted from worker model)

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/api/worker/worker.go [hunk 1]
```diff
@@ -313,14 +313,40 @@ func RegisterWorker(db *gorp.DbMap, name string, key string, modelID int64, hatc
...
+				if !found {
+					capaToDelete = append(capaToDelete, existingCapa.Value)
+				}
+			}
+
+			if len(capaToDelete) > 0 {
+				log.Debug("Updating model %d binary capabilities with %d capabilities to delete", modelID, len(capaToDelete))
+				for _, capa := range capaToDelete {
+					query := `DELETE FROM worker_capability WHERE worker_model_id=$1 AND name=$2 AND argument=$3 AND type=$4`
+					if _, err := db.Exec(query, modelID, capa, capa, string(sdk.BinaryRequirement)); err != nil {
```
Comment (fsamin) [inline engine/api/worker/worker.go]: it would be better do run only one request with `DELETE FROM worker_capability WHERE worker_model_id=$1 AND name IN (%s)  AND type=$2`, strings.Join(capaToDelete)

**Comment by ovh-cds** [comment]
CDS Report ut-engine#6932.1 ✘  
* Stage 1
  * Engine Test with DB ✘
