### PR TITLE
fix (api): export application deployment strategies.

### LINKED ISSUE #2867: Bug: pushing application "as code" invalidates platform tokens
After a `cdsctl workflow push` containing an application, it is impossible to deploy this application on a platform, with the error:

```
1 | Starting step /DeployApplication-1
-- | --
2 | # Plugin OVH Arsenal Deployment Plugin vsnapshot is ready
3 | Deploying LhasaPreview on Arsenal at http://arsenal....
4 | # Details: deployment failure
5 | # Status: Fail
6 | Body:  {"error":"bad token: encoding/hex: invalid byte: U+002A '*'"}
```

Resetting the platform token fix the issue

### PR DESCRIPTION
**Pull request by sguiheux**
1. Description
1. Related issues
#2867 
1. About tests
1. Mentions
@ovh/cds

close #2867

### CODE REVIEW

File: sdk/platform.go [hunk 1]
```diff
@@ -149,15 +149,17 @@ func (pf *ProjectPlatform) HideSecrets() {
 
 // MergeWith merge two config
 func (config *PlatformConfig) MergeWith(cfg PlatformConfig) {
-	if config == nil {
+	if *config == nil {
```
Comment (fsamin) [inline sdk/platform.go]: i think you should test `config == nil` i.e the pointer to the underlying map is nil and `*config == nil` i.e. the pointer is valid but the the underlying map is nil (has never been initialized)

File: engine/api/project/key.go [hunk 2]
```diff
@@ -81,8 +79,15 @@ func EncryptWithBuiltinKey(db gorp.SqlExecutor, projectID int64, name, content s
 		EncyptedContent: []byte(s),
 	}
 
-	if err := db.Insert(&bded); err != nil {
-		return "", sdk.WrapError(err, "DecryptWithBuiltinKey> Unable to save encrypted_data")
+	if existingToken != "" {
+		bded.Token = existingToken
+		if _, err := db.Update(&bded); err != nil {
+			return "", sdk.WrapError(err, "DecryptWithBuiltinKey> Unable to update encrypted_data")
```
Comment (bnjjj) [inline engine/api/project/key.go]: s/DecryptWithBuiltinKey/EncryptWithBuiltinKey

File: engine/api/project/key.go [hunk 3]
```diff
@@ -81,8 +79,15 @@ func EncryptWithBuiltinKey(db gorp.SqlExecutor, projectID int64, name, content s
...
+		}
+	} else {
+		if err := db.Insert(&bded); err != nil {
+			return "", sdk.WrapError(err, "DecryptWithBuiltinKey> Unable to save encrypted_data")
```
Comment (bnjjj) [inline engine/api/project/key.go]: s/DecryptWithBuiltinKey/EncryptWithBuiltinKey
