### PR TITLE
fix(api): artifactDownload as code

### LINKED ISSUE #3637: fix(sdk): artifact download as code
i miss the pattern parameter :/
and there should be only `artifactDownload: <pattern>`
screen shot 2018-11-22 at 16 43 53

### PR DESCRIPTION
**Pull request by yesnault**
close #3637

### CODE REVIEW

File: sdk/exportentities/action.go [hunk 1]
```diff
@@ -109,6 +109,14 @@ func newSteps(a sdk.Action) []Step {
 				if application != nil {
 					artifactDownloadArgs["application"] = application.Value
 				}
+				pattern := sdk.ParameterFind(&act.Parameters, "pattern")
+				if pattern != nil {
+					artifactDownloadArgs["pattern"] = pattern.Value
+				}
+				enabled := sdk.ParameterFind(&act.Parameters, "enabled")
+				if enabled != nil && enabled.Value == "false" {
```
Comment (richardlt) [inline sdk/exportentities/action.go]: Why setting this only if false ?

Comment (yesnault) [reply sdk/exportentities/action.go]: default value -> no attr on yml
