### PR TITLE
fix(api): some fixes about transform to as code (close #4037)

### LINKED ISSUE #4037: fix(api): transform workflow as code , loose workflow icon
and i'm not able to set it anymore

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
close #4037 
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/api/workflow/dao.go [hunk 1]
```diff
@@ -1736,3 +1745,17 @@ func IsDeploymentIntegrationUsed(db gorp.SqlExecutor, projectID int64, appID int
 
 	return nb > 0, nil
 }
+
+// loadWorkflowIcon load the workflow icon given its id
+func loadWorkflowIcon(db gorp.SqlExecutor, workflowID int64) (string, error) {
```
Comment (golangcibot) [inline engine/api/workflow/dao.go]: `loadWorkflowIcon` is unused (from `deadcode`)

**Comment by ovh-cds** [comment]
CDS Report ut-engine#9146.0 ✘  
* Stage 1
  * Engine Test with DB ✘
