### PR TITLE
fix(api): when you update repomanager on an application, update workflow root linked

### LINKED ISSUE #2913: Remove repository webhook on application repository modification

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
1. About tests
close  #2913
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/api/repositories_manager.go [hunk 1]
```diff
@@ -487,15 +538,64 @@ func (api *API) detachRepositoriesManagerHandler() Handler {
...
+					hookToDelete[nodeHook.UUID] = nodeHook
+				}
+			}
+
+			if len(hookToDelete) > 0 {
+				txDel, errTx := db.Begin()
+				if errTx != nil {
+					return sdk.WrapError(errTx, "detachRepositoriesManager> Cannot create delete transaction")
+				}
+				defer txDel.Rollback()
```
Comment (golangci) [inline engine/api/repositories_manager.go]: Error return value of `txDel.Rollback` is not checked

**Comment by bnjjj** [comment]
@fsamin I think a warning is already generated
