### PR TITLE
fix(api): Add check on import application as code #3711

### LINKED ISSUE #3711: Add check on import application as code
```
version: v1.0
name: cds-workflows
vcs_server: my-serveur
repo: foo/bar
vcs_connection_type: ssh
vcs_pgp_key: app-pgp-key
```

if connection type is ssh, we must return an error if there is no ssh key provided vcs_ssh_key

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
close #3711
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/api/application/application_parser.go [hunk 1]
```diff
@@ -130,6 +130,9 @@ func ParseAndImport(db gorp.SqlExecutor, cache cache.Store, proj *sdk.Project, e
 	if app.RepositoryStrategy.ConnectionType == "" {
 		app.RepositoryStrategy.ConnectionType = "https"
 	}
+	if app.RepositoryStrategy.ConnectionType == "ssh" && app.RepositoryStrategy.SSHKey == "" {
+		return app, nil, sdk.WrapError(sdk.ErrInvalidApplicationRepoStrategy, "Could not import application %s with a connection type ssh without ssh key", app.Name)
```
Comment (richardlt) [inline engine/api/application/application_parser.go]:
```suggestion
		return app, nil, sdk.NewErrorFrom(sdk.ErrInvalidApplicationRepoStrategy, "Could not import application %s with a connection type ssh without ssh key", app.Name)
```
