### PR TITLE
fix(hatchery): double check flag need registration

### LINKED ISSUE #5750: Worker models error
Hi,

I need help to solve an issue related to worker models.
We use CDS 0.48 release version on fresh install environment. 
Workers are spawned on a swarm hatchery launched on remote server and CDS is launched with docker-compose, the registration of worker model seems to be good but worker model is in error. 

Console output on worker model into CDS UI, display this (no specific error) :
`       p2021-03-01T18:34:18.394199372Z    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       n2021-03-01T18:34:18.394241759Z                                   Dload  Upload   Total   Spent    Left  Speed
        2021-03-01T18:34:18.472359704Z  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19.8M  100 19.8M    0     0   254M      0 --:--:-- --:--:-- --:--:--  254M
       S2021-03-01T18:34:18.488106774Z  2021-03-01 18:34:18  [32m[INFO] [0m Registering with Token eyJhbGciOiJS on http://192.168.0.100:8081  [32mcaller [0m github.com/ovh/cds/engine/worker/internal.(*CurrentWorker).Register  [32msource file [0m /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/worker/internal/register.go  [32msource line [0m 15
       )2021-03-01T18:34:18.575704514Z  2021-03-01 18:34:18  [32m[INFO] [0m Unregistering worker  [32mcaller [0m github.com/ovh/cds/engine/worker/internal.(*CurrentWorker).Unregister  [32msource file [0m /tmp/790ad7b9a1a85167593986ed564384b7/run/engine/worker/internal/register.go  [32msource line [0m 66`

Debug log on hatchery and no revelant error in it.
The only warning error that we can see is on CDS API:
`[WARN] service.JWTMiddleware> invalid given jwt token [/auth/consumer/worker/signin]: crypto/rsa: verification error` 

FYI, same environment works perfectly with CDS 0.47 and we try to setup into 2 differents environments.

Thanks in advance for help
Gilles

### PR DESCRIPTION
**Pull request by yesnault**
close #5750

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

File: sdk/hatchery/register.go [hunk 1]
```diff
@@ -92,15 +92,40 @@ loopModels:
...
 		}
 	}
+	if !sendError {
+		// need registration is false, no error to return
+		return nil
+	}
+
+	// it's need registration = true ->
+	// perhaps that the models list is not up to date
+	// so, we call a fresh model list to re-check the flag need registration kwowned by the api
```
Comment (richardlt) [inline sdk/hatchery/register.go:110]:
```suggestion
	// so, we call a fresh model list to re-check the flag need registration known by the api
```

**Review by fsamin — APPROVED** [review]

**Review by richardlt — APPROVED** [review]

**Review by sguiheux — APPROVED** [review]
