### PR TITLE
fix (api): workflow migrate permissions

### LINKED ISSUE #2073: workflow migrate permissions
old to new workflows -> take permission from application RWX and WX (and not only RWX from project)

### PR DESCRIPTION
**Pull request by yesnault**
close #2073

### CODE REVIEW

File: engine/api/migrate/migrate_workflow.go [hunk 1]
```diff
@@ -33,7 +33,8 @@ func MigrateToWorkflow(db gorp.SqlExecutor, store cache.Store, cdTree []sdk.CDPi
 			ProjectID:  proj.ID,
 			ProjectKey: proj.Key,
 		}
-		addGroupOnWorkflow(&newW, proj)
+
+		addGroupOnWorkflow(db, &newW, &oldW.Application)
```
Comment (bnjjj) [inline engine/api/migrate/migrate_workflow.go]: Error handling ?
