### PR TITLE
fix(api): mutex as-code

### LINKED ISSUE #4551: fix(api): export mutex attribute as code
it's not exported

### PR DESCRIPTION
**Pull request by yesnault**
close #4551

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

File: sdk/exportentities/workflow.go [hunk 1]
```diff
@@ -436,6 +439,9 @@ func (w Workflow) CheckValidity() error {
 		if len(w.DependsOn) != 0 {
 			mError.Append(fmt.Errorf("Error: wrong usage: depends_on not allowed here"))
 		}
+		if w.OneAtATime != nil && *w.OneAtATime != true && *w.OneAtATime != false {
```
Comment (golangcibot) [inline sdk/exportentities/workflow.go]: S1002: should omit comparison to bool constant, can be simplified to `!*w.OneAtATime` (from `gosimple`)

File: sdk/exportentities/workflow.go [hunk 2]
```diff
@@ -578,6 +584,10 @@ func (w Workflow) GetWorkflow() (*sdk.Workflow, error) {
 }
 
 func (e *NodeEntry) getNode(name string, w *sdk.Workflow) (*sdk.Node, error) {
+	var mutex bool
+	if e.OneAtATime != nil && *e.OneAtATime == true {
```
Comment (golangcibot) [inline sdk/exportentities/workflow.go]: S1002: should omit comparison to bool constant, can be simplified to `*e.OneAtATime` (from `gosimple`)

File: sdk/exportentities/workflow_test.go [hunk 3]
```diff
@@ -1036,6 +1063,31 @@ workflow:
     - aa_2
     when:
     - manual
+`,
+		},
+		{
+			name: "Join with condition",
```
Comment (fsamin) [inline sdk/exportentities/workflow_test.go]: wrong name

File: sdk/exportentities/workflow_test.go [hunk 4]
```diff
@@ -1036,6 +1063,31 @@ workflow:
...
+			yaml: `name: mymutex
+version: v1.0
+one_at_a_time: true
+pipeline: env
+`,
+		},
+		{
+			name: "Join with condition",
```
Comment (fsamin) [inline sdk/exportentities/workflow_test.go]: wrong name

File: sdk/exportentities/workflow_test.go [hunk 5]
```diff
@@ -218,13 +221,36 @@ func TestWorkflow_GetWorkflow(t *testing.T) {
...
+						Name: "pipeline",
+						Type: "pipeline",
+						Context: &sdk.NodeContext{
+							PipelineName: "pipeline",
+							Mutex:        true,
+						},
+					},
+				},
+			},
+		},
```
Comment (fsamin) [inline sdk/exportentities/workflow_test.go]: i miss a test with several pipelines

Comment (yesnault) [reply sdk/exportentities/workflow_test.go]: already done on `Complexe workflow without joins and mutex should not raise an error`
