### PR TITLE
fix(api): No hatchery can spawn a worker msg

### LINKED ISSUE #3318: fix(ui): No hatchery can spawn a worker corresponding your job's requirements. Please check your job's requirements.
Seen in logs:

`No hatchery can spawn a worker corresponding your job's requirements. Please check your job's requirements.`

Few seconds after, the worker is spawned, DISRUPTIVE!

### PR DESCRIPTION
**Pull request by yesnault**
close #3318

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

File: sdk/hatchery/starter.go [hunk 1]
```diff
@@ -25,16 +25,14 @@ type workerStarterRequest struct {
...
 	registerWorkerModel *sdk.Model
 }
 
 type workerStarterResult struct {
-	request      workerStarterRequest
-	isRun        bool
-	temptToSpawn bool
-	err          error
+	request workerStarterRequest
+	isRun   bool
```
Comment (golangcibot) [inline sdk/hatchery/starter.go]: `isRun` is unused (from `structcheck`)

File: sdk/hatchery/starter.go [hunk 2]
```diff
@@ -25,16 +25,14 @@ type workerStarterRequest struct {
...
+	err     error
```
Comment (golangcibot) [inline sdk/hatchery/starter.go]: `err` is unused (from `structcheck`)

File: sdk/hatchery/starter.go [hunk 3]
```diff
@@ -25,16 +25,14 @@ type workerStarterRequest struct {
...
 	workflowNodeRunID   int64
 	registerWorkerModel *sdk.Model
 }
 
 type workerStarterResult struct {
-	request      workerStarterRequest
-	isRun        bool
-	temptToSpawn bool
-	err          error
+	request workerStarterRequest
```
Comment (golangcibot) [inline sdk/hatchery/starter.go]: `request` is unused (from `structcheck`)
