### PR TITLE
fix(api): clean builtin artifact actions

### LINKED ISSUE #4020: Clean action arfifact upload/download
Remove old parameters ( application, pipeline ...)

### PR DESCRIPTION
**Pull request by fsamin**
1. Description
Clean builtin action on bootstap, by allowing the bootstrap to create or update the actions.
Add a 0.39 migration to remove all the useless parameters on all the pipelines
1. Related issues
close #4020
1. About tests
Manually on dev and preprod env
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/api/migrate/pipeline.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+
+	log.Info("migrate>CleanArtifactBuiltinActions> Start migration")
+
+	var all []struct {
+		ProjectKey   string `db:"projectkey"`
+		PipelineName string `db:"name"`
+	}
+
+	query := `SELECT project.projectkey, pipeline.name FROM pipeline JOIN project on project.id = pipeline.project_id`
+	db.Select(&all, query)
```
Comment (golangcibot) [inline engine/api/migrate/pipeline.go]: Error return value of `db.Select` is not checked (from `errcheck`)

**Comment by fsamin** [comment]
still need to check in preprod
