### PR TITLE
fix(worker): download in the current directory

### LINKED ISSUE #4095: workflow download does not download in current directory
workflow download does not download in current directory (as it says on console), but in {{.cds.workspace}}

Extract from a run of CDS with bash -ex
```
+ cd /cicd/models
+ worker download --workflow=cicd.models --number=5 '--pattern=\.tar$'
Downloading artifacts from into current directory
downloading artifact debian7.tar with tag 5-5 from workflow PCS/cicd.models on run 5...
cicd.models.5.debian9.log does not match pattern \.tar$ - skipped
cicd.models.5.log does not match pattern \.tar$ - skipped
cicd.models.5.debian7.log does not match pattern \.tar$ - skipped
+ ls -lh
total 0
+ find / -name debian7.tar
/tmp/Q0lDRA/run/debian7.tar
```

### PR DESCRIPTION
**Pull request by fsamin**
close #4095

### CODE REVIEW

File: engine/worker/cmd_download.go [hunk 1]
```diff
@@ -85,11 +87,13 @@ func downloadCmd(w *currentWorker) func(cmd *cobra.Command, args []string) {
 			}
 		}
 
+		wd, _ := os.Getwd()
```
Comment (bnjjj) [inline engine/worker/cmd_download.go]: error handling

Comment (fsamin) [reply engine/worker/cmd_download.go]: not useful, if the working directory is empty; it will be downloaded in the worker home directory
