### PR TITLE
fix(api): do not allow user run a workflow with cds. in payload #4230

### LINKED ISSUE #4230: Do not allow . cds.* in payload
User must not overwrite cds variable

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
close #4230
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: sdk/error.go [hunk 1]
```diff
@@ -531,6 +533,7 @@ var errorsFrench = map[int]string{
 	ErrWorkflowAsCodeOverride.ID:                        "Vous ne pouvez pas importer le workflow depuis ce dépôt",
 	ErrProjectSecretDataUnknown.ID:                      "Donnée chiffrée non valide",
 	ErrApplicationMandatoryOnWorkflowAsCode.ID:          "Une application liée à un dépôt git est obligatoire à la racine du workflow",
+	ErrInvalidPayloadVariable.ID:                        "Le payload du workflow ne peut pas contenir de clés nommées cds.*",
```
Comment (yesnault) [inline sdk/error.go]:
```suggestion
	ErrInvalidPayloadVariable.ID:                        "Le payload du workflow ne peut pas contenir de clé nommée cds.*",
```

File: sdk/error.go [hunk 2]
```diff
@@ -360,167 +361,168 @@ var errorsAmericanEnglish = map[int]string{
 	ErrWorkflowAsCodeOverride.ID:                        "You cannot override workflow from this repository",
 	ErrProjectSecretDataUnknown.ID:                      "Invalid encrypted data",
 	ErrApplicationMandatoryOnWorkflowAsCode.ID:          "An application linked to a git repository is mandatory on the workflow root",
+	ErrInvalidPayloadVariable.ID:                        "Your payload cannot contain keys like cds.*",
```
Comment (yesnault) [inline sdk/error.go]:
```suggestion
	ErrInvalidPayloadVariable.ID:                        "Your payload cannot contain key like cds.*",
```
