### PR TITLE
fix(api): release book after worker model registration or error

### LINKED ISSUE #3862: Remove redis book entry after register
When a worker model finished to register, we must delete the redis entry book:workermodel:<id>

### PR DESCRIPTION
**Pull request by fsamin**
close #3862

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report it#8881.0 ✘  
* w-it
  * w-it ✘

File: engine/api/worker.go [hunk 1]
```diff
@@ -36,18 +36,23 @@ func (api *API) registerWorkerHandler() service.Handler {
...
+		log.Debug("New worker: [%s] - %s", wk.ID, wk.Name)
+
+		if params.RegistrationOnly {
+			log.Debug("removing book from cache : %+v", params)
+			worker.UnbookForRegister(api.Cache, params.ModelID)
+		}
 
 		// Return worker info to worker itself
-		return service.WriteJSON(w, worker, http.StatusOK)
+		return service.WriteJSON(w, w, http.StatusOK)
```
Comment (yesnault) [inline engine/api/worker.go]: it's not wk?

Comment (fsamin) [reply engine/api/worker.go]: true
