### PR TITLE
fix (sdk): import pipeline with only 1 job with requirements

### LINKED ISSUE #760: Requirements not set on pipeline import
When I try to import the following yaml, everything went fine except the requirements which are not imported.

```
name: build-all-images
type: build
requirements:
- hostname: buildbot_image
- binary: git
steps:
- script: |-
    #!/bin/bash

    echo "I'm just a decoy allowing you to rebuild the images."

    exit 0;
```

### PR DESCRIPTION
**Pull request by fsamin**
closes #760

### CODE REVIEW

File: sdk/exportentities/pipeline.go [hunk 1]
```diff
@@ -159,6 +159,40 @@ func (s Step) AsJUnitReport() (*sdk.Action, bool, error) {
 	return &a, true, nil
 }
 
+func (s Step) AsGitClone() (*sdk.Action, bool, error) {
```
Comment (yesnault) [inline sdk/exportentities/pipeline.go]: doc

File: sdk/exportentities/pipeline.go [hunk 2]
```diff
@@ -159,6 +159,40 @@ func (s Step) AsJUnitReport() (*sdk.Action, bool, error) {
...
+	}
+	a.Final, err = s.IsFinal()
+	if err != nil {
+		return nil, true, err
+	}
+
+	return &a, true, nil
+}
+
 func (s Step) AsArtifactUpload() (*sdk.Action, bool, error) {
```
Comment (yesnault) [inline sdk/exportentities/pipeline.go]: doc
