### PR TITLE
fix (api): update lastModified app on add grp

### LINKED ISSUE #769: fix (api): group permission & last update app/pip

### PR DESCRIPTION
**Pull request by yesnault**
close #769

### CODE REVIEW

File: engine/api/project_group.go [hunk 1]
```diff
@@ -72,78 +61,59 @@ func updateGroupRoleOnProjectHandler(w http.ResponseWriter, r *http.Request, db
...
 	}
 
-	p, err := project.Load(db, key, c.User)
-	if err != nil {
-		log.Warning("updateGroupRoleHandler: Cannot load %s: %s\n", key, err)
-		return sdk.ErrNoProject
-
+	p, errl := project.Load(db, key, c.User)
+	if errl != nil {
+		return sdk.WrapError(sdk.ErrNoProject, "updateGroupRoleHandler: Cannot load %s: %s", key, errl)
```
Comment (sguiheux) [inline engine/api/project_group.go]: sdk.WrapError ( err1,

File: engine/api/project_group.go [hunk 2]
```diff
@@ -72,78 +61,59 @@ func updateGroupRoleOnProjectHandler(w http.ResponseWriter, r *http.Request, db
...
 	}
 
-	g, err := group.LoadGroup(db, groupProject.Group.Name)
-	if err != nil {
-		log.Warning("updateGroupRoleHandler: Cannot find %s: %s\n", groupProject.Group.Name, err)
-		return sdk.ErrGroupNotFound
-
+	g, errlg := group.LoadGroup(db, groupProject.Group.Name)
+	if errlg != nil {
+		return sdk.WrapError(sdk.ErrGroupNotFound, "updateGroupRoleHandler: Cannot find %s: %s", groupProject.Group.Name, errlg)
```
Comment (sguiheux) [inline engine/api/project_group.go]: idem
