### PR TITLE
fix(api): edit as code worker model with a non-admin user

### LINKED ISSUE #3819: fix(ui): edit as code worker model with a non-admin user
capture d ecran 2019-01-05 a 11 45 50

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
close #3819 
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: sdk/exportentities/worker_model.go [hunk 1]
```diff
@@ -53,15 +70,15 @@ func NewWorkerModel(wm sdk.Model) WorkerModel {
 		model.PostCmd = wm.ModelVirtualMachine.PostCmd
 	}
 
+	for _, opt := range opts {
+		opt(wm, &model)
```
Comment (golangcibot) [inline sdk/exportentities/worker_model.go]: Error return value of `opt` is not checked (from `errcheck`)

File: engine/api/worker/model_import.go [hunk 2]
```diff
@@ -55,41 +51,33 @@ currentUGroup:
 		return nil, sdk.ErrWorkerModelNoAdmin
 	}
 
+	var badRequestError error
+	asSimpleUser := !u.Admin && !sdkWm.Restricted
```
Comment (richardlt) [inline engine/api/worker/model_import.go]: The following code is not really clear, its hard to understand what are the rules for a admin vs normal user and this is mixed with restricted and pattern usage...

File: engine/api/api_routes.go [hunk 3]
```diff
@@ -364,7 +364,7 @@ func (api *API) InitRouter() {
 	r.Handle("/worker/model/type", r.GET(api.getWorkerModelTypesHandler))
 	r.Handle("/worker/model/communication", r.GET(api.getWorkerModelCommunicationsHandler))
 	r.Handle("/worker/model/{permModelID}", r.PUT(api.updateWorkerModelHandler), r.DELETE(api.deleteWorkerModelHandler))
-	r.Handle("/worker/model/{permModelID}/export", r.GET(api.getWorkerModelExportHandler))
+	r.Handle("/worker/model/{modelID}/export", r.GET(api.getWorkerModelExportHandler))
```
[the remark this answers is not in the document]
Comment (bnjjj) [reply engine/api/api_routes.go]: It's ISO as it's done for worker model GET api

[the remark this answers is not in the document]
Comment (richardlt) [reply engine/api/api_routes.go]: Issue created #4125

File: engine/api/worker/model_import.go (hunk 2 above)
Comment (richardlt) [reply engine/api/worker/model_import.go]: ok

**Comment by ovh-cds** [comment]
CDS Report build-cds-doc#9022.0 ✘  
* Stage 1
  * New Job ✘

**Comment by ovh-cds** [comment]
CDS Report it#9024.1 ✘  
* w-it
  * w-it ✘
