### PR TITLE
fix(api): keep spawnInfos on stop

### LINKED ISSUE #3699: fix(api): spawn infos disapear
Steps to reproduce : 
+ Have a job with a requirement model and a binary which is not in the model
+ Launch this job
+ You can see multiple spawn infos and several which indicate that our binary isn't good
+ Stop the job. Then the spawn infos disapear

### PR DESCRIPTION
**Pull request by yesnault**
close #3699

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

File: engine/api/workflow/execute_node_run.go [hunk 1]
```diff
@@ -693,7 +693,7 @@ func stopWorkflowNodePipeline(ctx context.Context, dbFunc func() *gorp.DbMap, st
 	wg.Wait()
 
 	// Update stages from node run
-	stopWorkflowNodeRunStages(nodeRun)
+	stopWorkflowNodeRunStages(dbFunc(), nodeRun)
```
Comment (fsamin) [inline engine/api/workflow/execute_node_run.go]: we should put a sql transaction in there
