### PR TITLE
fix(api,ui): add pipeline name or workflow name in a new import route  for edit as code ui

### LINKED ISSUE #3009: fix(api,ui): add pipeline name or workflow name in a new import route for edit as code ui
In order to not erase modifications or create another pipeline when you change pipeline/workflow name.

add a check on name in route and in yaml

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
close #3009 
1. About tests
unit tests
1. Mentions
cc @Alkorin 

@ovh/cds

### CODE REVIEW

File: engine/api/pipeline_import.go [hunk 1]
```diff
@@ -157,3 +157,103 @@ func (api *API) importPipelineHandler() Handler {
...
+		if errorParse != nil {
+			return sdk.WrapError(sdk.ErrWrongRequest, "putImportPipelineHandler> Cannot parsing: %s", errorParse)
+		}
+
+		tx, errBegin := api.mustDB().Begin()
+		if errBegin != nil {
+			return sdk.WrapError(errBegin, "putImportPipelineHandler: Cannot start transaction")
+		}
+
+		defer tx.Rollback()
```
Comment (golangci) [inline engine/api/pipeline_import.go]: Error return value of `tx.Rollback` is not checked

File: engine/api/workflow_import.go [hunk 2]
```diff
@@ -125,7 +125,83 @@ func (api *API) postWorkflowImportHandler() Handler {
...
+
+		if errw != nil {
+			return sdk.NewError(sdk.ErrWrongRequest, errw)
+		}
+
+		tx, errtx := api.mustDB().Begin()
+		if errtx != nil {
+			return sdk.WrapError(errtx, "postWorkflowImportHandler> Unable to start tx")
+		}
+		defer tx.Rollback()
```
Comment (golangci) [inline engine/api/workflow_import.go]: Error return value of `tx.Rollback` is not checked

**Comment by ovh-cds** [comment]
CDS Report build-engine-cli-tools#4953.0 ✘  
* Build minimal
  * cds cli legacy ✔ 
  * cdsctl linux ✔ 
  * Engine Build linux amd64 ✔ 
  * tools/debpacker ✔ 
  * tools/os-ansible-inventory ✔ 
  * Worker linux amd64 / 386 ✔ 
* Build other os/arch
  * cds cli legacy darwin/windows amd64 -  
  * cdsctl darwin -  
  * cdsctl freebsd amd64 -  
  * Doc Build -  
  * Engine Build darwin amd64 -  
  * Engine Build freebsd amd64 -  
  * Engine Build linux arm -  
  * Engine Build windows amd64 -  
  * Plugins darwin amd64 -  
  * Plugins freebsd -  
  * Plugins linux amd64 -  
  * Plugins linux arm -  
  * Plugins windows amd64 -  
  * Worker darwin / windows / freebsd -  
  * Worker linux arm -  
* Package
  * Debian Engine Package ✘  
  * Docker Engine Package ✘
