### PR TITLE
fix(api): catch locked element and add retry in sdk if it's locked (close #3581)

### LINKED ISSUE #3581: fix(worker): add retry on postWorkflowJobTestsResultsHandler
```pprofLabel>recoverWrap>Handle>postWorkflowJobTestsResultsHandler>LoadAndLockNodeRunByID: internal server error (caused by: Cannot load node job: Unable to load workflow_node_run node=2604599: pq: could not obtain lock on row in relation "workflow_node_run")```

we should handle the pq error `pq: could not obtain lock on row in relation "workflow_node_run"`to handle retry on all client function retries on this kind of error at client http level

```go
func (c *client) QueueSendResult(ctx context.Context, id int64, res sdk.Result) error {
	path := fmt.Sprintf("/queue/workflows/%d/result", id)
	_, err := c.PostJSON(ctx, path, res, nil)
	return err
}
```

### PR DESCRIPTION
**Pull request by bnjjj**
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

1. Description
1. Related issues
1. About tests
1. Mentions

@ovh/cds

### CODE REVIEW

File: engine/worker/builtin_junit.go [hunk 1]
```diff
@@ -93,13 +95,21 @@ func runParseJunitTestResultAction(w *currentWorker) BuiltInAction {
...
+		var errPost error
+		for retry := 0; retry < 10; retry++ {
+			_, statusCode, errPost = sdk.Request("POST", uri, []byte(dataS))
+			if statusCode != http.StatusConflict {
+				break
+			}
+			time.Sleep(500 * time.Millisecond)
+		}
+		if errPost == nil && statusCode > 300 {
+			err = fmt.Errorf("HTTP %d", statusCode)
```
Comment (golangcibot) [inline engine/worker/builtin_junit.go]: ineffectual assignment to `err`
