### PR TITLE
fix(api): avoid worker model name with space

### LINKED ISSUE #4602: avoid worker model with space in name

### PR DESCRIPTION
**Pull request by yesnault**
close #4602

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com>

### CODE REVIEW

File: sdk/worker_model.go [hunk 1]
```diff
@@ -108,9 +108,10 @@ func (m *Model) Update(data Model) {
 
 // IsValid returns error if the model is not valid.
 func (m Model) IsValid() error {
-	if m.Name == "" {
-		return WrapError(ErrWrongRequest, "invalid worker model name")
+	if !NamePatternRegex.MatchString(m.Name) {
+		return WrapError(ErrInvalidWorkerModelNamePattern, "worker model name %s does not respect pattern %s", m.Name, NamePattern)
```
Comment (fsamin) [inline sdk/worker_model.go]: redundant wrap message, just return the error with stack

Comment (yesnault) [reply sdk/worker_model.go]: seen both
