### PR TITLE
fix (ui): play / relaunch / stop workflow & pipeline btn displayed for readers

### LINKED ISSUE #2085: fix (ui): play / relaunch / stop workflow & pipeline btn displayed for readers
and theses buttons should be disabled or hidden

### PR DESCRIPTION
**Pull request by bnjjj**
close #2085

Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

### CODE REVIEW

File: engine/api/workflow/dao_node.go [hunk 1]
```diff
@@ -304,30 +302,30 @@ func LoadNodeContextByNodeName(db gorp.SqlExecutor, store cache.Store, proj *sdk
 	}
 	ctx := sdk.WorkflowNodeContext(dbnc)
 
-	if err := postLoadNodeContext(db, store, &ctx, opts); err != nil {
+	if err := postLoadNodeContext(db, store, proj.Key, nil, &ctx, opts); err != nil {
```
Comment (fsamin) [inline engine/api/workflow/dao_node.go]: Nil ?
